eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1305/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: clients-services
            uri: http://localhost:1306
            predicates:
              - Path=/api/clients/**
          - id: produits-services
            uri: http://localhost:1414
            predicates:
              - Path=/api/produits/**
          - id: user-services
            uri: http://localhost:1399
            predicates:
              - Path=/api/users/**
          - id: registration-service
            uri: http://localhost:1381
            predicates:
              - Path=/api/registrations/**



server:
  port: 2020